In [13]:
import pandas as pd
import numpy as np

In [14]:
sentences = [
    "The weather is so pleasant today",
    "I enjoyed the book I read last night",
    "Her kindness made everyone smile",
    "The sunset over the lake was breathtaking",
    "I feel so motivated to start a new project",
    "The performance was outstanding and memorable",
    "This park is the perfect place to relax",
    "I am proud of the progress we’ve made",
    "Helping someone in need always feels rewarding",
    "Tomorrow holds so much promise and hope",
    "The room is too cluttered and uncomfortable",
    "I find it hard to focus in such noisy surroundings",
    "The movie was boring and dragged on for too long",
    "The customer service was unhelpful and rude",
    "I regret not being more prepared for the meeting",
    "Your creativity always amazes me",
    "The cake you baked tastes incredible",
    "It feels so satisfying to complete a challenging task",
    "The garden is blooming with vibrant colors",
    "Spending time with loved ones always makes my day better"
]

In [65]:
labels = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [17]:
tokens = Tokenizer(oov_token = 'oov')
tokens.fit_on_texts(sentences)

In [18]:
vocab = tokens.word_index

In [19]:
vocab

{'oov': 1,
 'the': 2,
 'i': 3,
 'and': 4,
 'is': 5,
 'so': 6,
 'was': 7,
 'to': 8,
 'always': 9,
 'made': 10,
 'a': 11,
 'in': 12,
 'feels': 13,
 'too': 14,
 'it': 15,
 'for': 16,
 'with': 17,
 'weather': 18,
 'pleasant': 19,
 'today': 20,
 'enjoyed': 21,
 'book': 22,
 'read': 23,
 'last': 24,
 'night': 25,
 'her': 26,
 'kindness': 27,
 'everyone': 28,
 'smile': 29,
 'sunset': 30,
 'over': 31,
 'lake': 32,
 'breathtaking': 33,
 'feel': 34,
 'motivated': 35,
 'start': 36,
 'new': 37,
 'project': 38,
 'performance': 39,
 'outstanding': 40,
 'memorable': 41,
 'this': 42,
 'park': 43,
 'perfect': 44,
 'place': 45,
 'relax': 46,
 'am': 47,
 'proud': 48,
 'of': 49,
 'progress': 50,
 'we’ve': 51,
 'helping': 52,
 'someone': 53,
 'need': 54,
 'rewarding': 55,
 'tomorrow': 56,
 'holds': 57,
 'much': 58,
 'promise': 59,
 'hope': 60,
 'room': 61,
 'cluttered': 62,
 'uncomfortable': 63,
 'find': 64,
 'hard': 65,
 'focus': 66,
 'such': 67,
 'noisy': 68,
 'surroundings': 69,
 'movie': 70,
 'boring':

In [51]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequence = tokenizer.texts_to_sequences(sentences)

print(sequence)

[[1, 17, 4, 5, 18, 19], [2, 20, 1, 21, 2, 22, 23, 24], [25, 26, 9, 27, 28], [1, 29, 30, 1, 31, 6, 32], [2, 33, 5, 34, 7, 35, 10, 36, 37], [1, 38, 6, 39, 3, 40], [41, 42, 4, 1, 43, 44, 7, 45], [2, 46, 47, 48, 1, 49, 50, 9], [51, 52, 11, 53, 8, 12, 54], [55, 56, 5, 57, 58, 3, 59], [1, 60, 4, 13, 61, 3, 62], [2, 63, 14, 64, 7, 65, 11, 66, 67, 68], [1, 69, 6, 70, 3, 71, 72, 15, 13, 73], [1, 74, 75, 6, 76, 3, 77], [2, 78, 79, 80, 81, 82, 15, 1, 83], [84, 85, 8, 86, 87], [1, 88, 89, 90, 91, 92], [14, 12, 5, 93, 7, 94, 10, 95, 96], [1, 97, 4, 98, 16, 99, 100], [101, 102, 16, 103, 104, 8, 105, 106, 107, 108]]


In [52]:
print(tokenizer.word_index)

{'the': 1, 'i': 2, 'and': 3, 'is': 4, 'so': 5, 'was': 6, 'to': 7, 'always': 8, 'made': 9, 'a': 10, 'in': 11, 'feels': 12, 'too': 13, 'it': 14, 'for': 15, 'with': 16, 'weather': 17, 'pleasant': 18, 'today': 19, 'enjoyed': 20, 'book': 21, 'read': 22, 'last': 23, 'night': 24, 'her': 25, 'kindness': 26, 'everyone': 27, 'smile': 28, 'sunset': 29, 'over': 30, 'lake': 31, 'breathtaking': 32, 'feel': 33, 'motivated': 34, 'start': 35, 'new': 36, 'project': 37, 'performance': 38, 'outstanding': 39, 'memorable': 40, 'this': 41, 'park': 42, 'perfect': 43, 'place': 44, 'relax': 45, 'am': 46, 'proud': 47, 'of': 48, 'progress': 49, 'we’ve': 50, 'helping': 51, 'someone': 52, 'need': 53, 'rewarding': 54, 'tomorrow': 55, 'holds': 56, 'much': 57, 'promise': 58, 'hope': 59, 'room': 60, 'cluttered': 61, 'uncomfortable': 62, 'find': 63, 'hard': 64, 'focus': 65, 'such': 66, 'noisy': 67, 'surroundings': 68, 'movie': 69, 'boring': 70, 'dragged': 71, 'on': 72, 'long': 73, 'customer': 74, 'service': 75, 'unhelpf

In [53]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequence= pad_sequences(sequence, maxlen=6, padding='post', truncating='post')

print(sequence)


[[  1  17   4   5  18  19]
 [  2  20   1  21   2  22]
 [ 25  26   9  27  28   0]
 [  1  29  30   1  31   6]
 [  2  33   5  34   7  35]
 [  1  38   6  39   3  40]
 [ 41  42   4   1  43  44]
 [  2  46  47  48   1  49]
 [ 51  52  11  53   8  12]
 [ 55  56   5  57  58   3]
 [  1  60   4  13  61   3]
 [  2  63  14  64   7  65]
 [  1  69   6  70   3  71]
 [  1  74  75   6  76   3]
 [  2  78  79  80  81  82]
 [ 84  85   8  86  87   0]
 [  1  88  89  90  91  92]
 [ 14  12   5  93   7  94]
 [  1  97   4  98  16  99]
 [101 102  16 103 104   8]]


In [54]:
sequence.shape

(20, 6)

In [55]:
sequence.shape[0]

20

In [58]:
labels = np.array(label).reshape(-1)

In [59]:
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [61]:
model = Sequential()

In [62]:
model.add(SimpleRNN(1, input_shape=(sequence.shape[1],1), activation = 'relu' ))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [63]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [66]:
print(f"Label length: {len(labels)}")
print(f"Sequence shape: {sequence.shape}")

Label length: 20
Sequence shape: (20, 6)


In [67]:
import numpy as np

sequence = np.array(sequence)
labels = np.array(labels)


model.fit(sequence, labels, epochs=5)


Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2500 - loss: 0.6931
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.6929
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.6926
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.6924
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.6921


In [68]:
test=["I'm having a bad day today"]

In [70]:
test = tokens.texts_to_sequences(test)

In [71]:
test = pad_sequences(test, padding = 'post', truncating = 'post', maxlen = 6)

In [72]:
test

array([[  1,   1,  11,   1, 108,  20]], dtype=int32)

In [73]:
test.shape

(1, 6)

In [74]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


array([[0.50124985]], dtype=float32)

In [75]:
tokens.word_index

{'oov': 1,
 'the': 2,
 'i': 3,
 'and': 4,
 'is': 5,
 'so': 6,
 'was': 7,
 'to': 8,
 'always': 9,
 'made': 10,
 'a': 11,
 'in': 12,
 'feels': 13,
 'too': 14,
 'it': 15,
 'for': 16,
 'with': 17,
 'weather': 18,
 'pleasant': 19,
 'today': 20,
 'enjoyed': 21,
 'book': 22,
 'read': 23,
 'last': 24,
 'night': 25,
 'her': 26,
 'kindness': 27,
 'everyone': 28,
 'smile': 29,
 'sunset': 30,
 'over': 31,
 'lake': 32,
 'breathtaking': 33,
 'feel': 34,
 'motivated': 35,
 'start': 36,
 'new': 37,
 'project': 38,
 'performance': 39,
 'outstanding': 40,
 'memorable': 41,
 'this': 42,
 'park': 43,
 'perfect': 44,
 'place': 45,
 'relax': 46,
 'am': 47,
 'proud': 48,
 'of': 49,
 'progress': 50,
 'we’ve': 51,
 'helping': 52,
 'someone': 53,
 'need': 54,
 'rewarding': 55,
 'tomorrow': 56,
 'holds': 57,
 'much': 58,
 'promise': 59,
 'hope': 60,
 'room': 61,
 'cluttered': 62,
 'uncomfortable': 63,
 'find': 64,
 'hard': 65,
 'focus': 66,
 'such': 67,
 'noisy': 68,
 'surroundings': 69,
 'movie': 70,
 'boring':